# Generated by Django 2.2.1 on 2019-05-12 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCompleto', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('idade', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=40)),
                ('numero', models.IntegerField()),
                ('ap', models.IntegerField(blank=True, max_length=10, null=True)),
                ('bloco', models.CharField(blank=True, max_length=8, null=True)),
                ('rua', models.CharField(blank=True, max_length=10, null=True)),
                ('quadra', models.CharField(blank=True, max_length=4, null=True)),
                ('bairro', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=20)),
                ('objetivo', models.TextField()),
                ('educacao', models.CharField(max_length=30)),
                ('nome', models.CharField(blank=True, max_length=40, null=True)),
                ('instituicao', models.CharField(blank=True, max_length=40, null=True)),
                ('empresa', models.CharField(blank=True, max_length=40, null=True)),
                ('cargo', models.CharField(blank=True, max_length=40, null=True)),
                ('periodo', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(blank=True, max_length=40, null=True)),
                ('dataExpedicao', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.Usuario')),
            ],
        ),
    ]
