# Generated by Django 2.2.1 on 2019-05-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_auto_20190512_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculo',
            options={'verbose_name_plural': 'Curriculo'},
        ),
        migrations.RenameField(
            model_name='curriculo',
            old_name='descricao',
            new_name='descricaoCertificado',
        ),
        migrations.RenameField(
            model_name='curriculo',
            old_name='nome',
            new_name='nomeCurso',
        ),
        migrations.AddField(
            model_name='curriculo',
            name='descricaoCurso',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curriculo',
            name='descricaoProfissao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
