# Generated by Django 2.2.1 on 2019-05-14 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_auto_20190512_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculo',
            name='senha',
        ),
    ]
